import re
import subprocess
import shlex

class LocalSandbox:
    def __init__(self, workspace_dir: str):
        """
        Initializes the restricted local execution environment.
        """
        self.workspace_dir = workspace_dir

    def parse_and_execute(self, ai_response: str) -> str:
        """
        Parses the AI's response for <tool_call> XML blocks and executes them.
        Returns the original response appended with the tool's output.
        """
        # Look for XML-style tool calls generated by Qwythos
        pattern = r"<tool_call>\s*(.*?)\s*</tool_call>"
        matches = re.findall(pattern, ai_response, re.DOTALL)
        
        if not matches:
            return ai_response
            
        execution_results = []
        for command in matches:
            # Clean up the command
            cmd_str = command.strip()
            result = self._execute_command(cmd_str)
            execution_results.append(f"\n[Sandbox Execution Output for '{cmd_str}']:\n{result}")
            
        return ai_response + "\n" + "".join(execution_results)

    def _execute_command(self, cmd_str: str) -> str:
        """
        Executes a command safely.
        WARNING: In a production Red Teaming tool, this needs strict OS-level 
        virtualization (like Docker/gVisor). Here we use subprocess with timeouts.
        """
        try:
            # Safely split the command string for subprocess
            args = shlex.split(cmd_str)
            
            # Execute with a strict timeout to prevent hanging reverse-shells
            process = subprocess.run(
                args,
                cwd=self.workspace_dir,
                capture_output=True,
                text=True,
                timeout=10
            )
            
            if process.returncode == 0:
                return process.stdout
            else:
                return f"Execution Failed:\n{process.stderr}"
                
        except subprocess.TimeoutExpired:
            return "Error: Command execution timed out."
        except Exception as e:
            return f"Sandbox Error: {str(e)}"
